matrix:
  include:
  - language: node_js
    node_js: '12'
    addons:
        sonarcloud:
            organization: 'swsnu'
            token:
                secure: 'fDte2zqGHs3+hC84I2t1SkozQDI8b9B/CkwX1YcfRF+cjbQIY0eIQJf4fcs7aQkfQZscAKeRVs5+1DbWhI1HGxDuT+U3DEqGyhM2RLCtlU2A8Wd7lZuuhsPnGevNtpVLiL7t0u9Ye5aadHf4DrOrop3pB8fjm/NIF1HJAWItPG/5G2lQ3e4IsKYLYD8oNM51TqQm9NxHdufknXDVaEfO6g8oWSqqES5DSHc7V9djFia/eyyLTfzf3zNpaxlM2gFCf2hAMLfWRUnYjdR3KiHGK5LagYAWe7Nvt8saB1q1kuj1u7p8/nFrnAB/yynM9HwpgI0A3n4TIYMlVTI6A5TYQrqsAxYhuD0SO77NnPizfIyJOzez8uE/MyMDKKpLQI+PNO8HvCLXAb3qkaVgZVNh6bXpvFQ2ABCNtCLuv678ccnnOswgAnzm584y/u8bs8qFxMaYSb6C5imAzHQiHc4EB0pLimqpjvUYl19UsilN3C3CLZS8uW3pBONzlhfTZGiRAbA/u5pBJilOi/N2jtKv8q508U1Wn17qVBqYXp05zIsCATVQBZqavdPEdUyIUcsuG4zmai+eWYrSrIXSOLRseadpZsslSonBLiVLpF0vgOgElD9rglL7y4bpkWMZcGipmxTsCfAM8ZrsjWEfaTVqYDnOJVuTklEyyRwT6i8Sh94='
    cache:
    - yarn: true
    before_install:
    - cd frontend
    install:
    - yarn install
    script:
    - yarn lint
    - yarn test --coverage --watchAll=false
    - cd .. && sonar-scanner
  - language: python
    python: '3.8'
    addons:
        sonarcloud:
            organization: 'swsnu'
            token:
                secure: 'fDte2zqGHs3+hC84I2t1SkozQDI8b9B/CkwX1YcfRF+cjbQIY0eIQJf4fcs7aQkfQZscAKeRVs5+1DbWhI1HGxDuT+U3DEqGyhM2RLCtlU2A8Wd7lZuuhsPnGevNtpVLiL7t0u9Ye5aadHf4DrOrop3pB8fjm/NIF1HJAWItPG/5G2lQ3e4IsKYLYD8oNM51TqQm9NxHdufknXDVaEfO6g8oWSqqES5DSHc7V9djFia/eyyLTfzf3zNpaxlM2gFCf2hAMLfWRUnYjdR3KiHGK5LagYAWe7Nvt8saB1q1kuj1u7p8/nFrnAB/yynM9HwpgI0A3n4TIYMlVTI6A5TYQrqsAxYhuD0SO77NnPizfIyJOzez8uE/MyMDKKpLQI+PNO8HvCLXAb3qkaVgZVNh6bXpvFQ2ABCNtCLuv678ccnnOswgAnzm584y/u8bs8qFxMaYSb6C5imAzHQiHc4EB0pLimqpjvUYl19UsilN3C3CLZS8uW3pBONzlhfTZGiRAbA/u5pBJilOi/N2jtKv8q508U1Wn17qVBqYXp05zIsCATVQBZqavdPEdUyIUcsuG4zmai+eWYrSrIXSOLRseadpZsslSonBLiVLpF0vgOgElD9rglL7y4bpkWMZcGipmxTsCfAM8ZrsjWEfaTVqYDnOJVuTklEyyRwT6i8Sh94='
    cache:
    - pip: true
    before_install:
    - cd backend
    install:
    - pip install -r requirements.txt
    script:
    - pylint **/*.py --load-plugins pylint_django
    - coverage run --source='.' manage.py test
    - coverage xml
    - cd .. && sonar-scanner
