# Generated by Django 3.1.3 on 2020-11-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='rep_img',
        ),
    ]
