# Generated by Django 3.1.3 on 2020-11-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_remove_place_rep_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rep_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
