# Generated by Django 3.1.3 on 2020-11-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20201109_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='gallery_thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
