# Generated by Django 3.1.3 on 2020-11-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20201122_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.DurationField(),
        ),
    ]
