# Generated by Django 3.1.3 on 2020-11-24 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reco_img', '0001_initial'),
        ('plan', '0007_auto_20201122_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cover_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_image', to='reco_img.reco_img'),
        ),
    ]
