# Generated by Django 3.1.3 on 2020-11-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_plan_cover_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='cover_img',
            new_name='reco_img',
        ),
    ]
